const cardsData = [
  {
    id: 1,
    category: "coffee",
    name: "Irish coffee",
    description: "Fragrant black coffee with Jameson Irish whiskey and whipped milk",
    price: "$7.00",
    src: "../resources/catalog/coffee-1.jpg",
    alt: "Irish coffee",
  },
  {
    id: 2,
    category: "coffee",
    name: "Kahlua coffee",
    description: "Classic coffee with milk and Kahlua liqueur under a cap of frothed milk",
    price: "$7.00",
    src: "../resources/catalog/coffee-2.jpg",
    alt: "Kahlua coffee",
  },
  {
    id: 3,
    category: "coffee",
    name: "Honey raf",
    description: "Espresso with frothed milk, cream and aromatic honey",
    price: "$5.50",
    src: "../resources/catalog/coffee-3.jpg",
    alt: "Honey raf",
  },
  {
    id: 4,
    category: "coffee",
    name: "Ice cappuccino",
    description: "Cappuccino with soft thick foam in summer version with ice",
    price: "$5.00",
    src: "../resources/catalog/coffee-4.jpg",
    alt: "Ice cappuccino",
  },
  {
    id: 5,
    category: "coffee",
    name: "Espresso",
    description: "Classic black coffee",
    price: "$5.00",
    src: "../resources/catalog/coffee-5.jpg",
    alt: "Espresso",
  },
  {
    id: 6,
    category: "coffee",
    name: "Latte",
    description: "Espresso coffee with the addition of steamed milk and dense milk foam",
    price: "$5.50",
    src: "../resources/catalog/coffee-6.jpg",
    alt: "Latte",
  },
  {
    id: 7,
    category: "coffee",
    name: "Latte macchiato",
    description: "Espresso with frothed milk and chocolate",
    price: "$5.50",
    src: "../resources/catalog/coffee-7.jpg",
    alt: "Latte macchiato",
  },
  {
    id: 8,
    category: "coffee",
    name: "Coffee with cognac",
    description: "Fragrant black coffee with cognac and whipped cream",
    price: "$6.50",
    src: "../resources/catalog/coffee-8.jpg",
    alt: "Coffee with cognac",
  },
  {
    id: 9,
    category: "tea",
    name: "Moroccan",
    description: "Fragrant black tea with the addition of tangerine, cinnamon, honey, lemon and mint",
    price: "$4.50",
    src: "../resources/catalog/tea-1.png",
    alt: "Moroccan",
  },
  {
    id: 10,
    category: "tea",
    name: "Ginger",
    description: "Original black tea with fresh ginger, lemon and honey",
    price: "$5.00",
    src: "../resources/catalog/tea-2.png",
    alt: "Ginger",
  },
  {
    id: 11,
    category: "tea",
    name: "Cranberry",
    description: "Invigorating black tea with cranberry and honey",
    price: "$5.00",
    src: "../resources/catalog/tea-3.png",
    alt: "Cranberry",
  },
  {
    id: 12,
    category: "tea",
    name: "Sea buckthorn",
    description: "Toning sweet black tea with sea buckthorn, fresh thyme and cinnamon",
    price: "$5.50",
    src: "../resources/catalog/tea-4.png",
    alt: "Sea buckthorn",
  },
  {
    id: 13,
    category: "dessert",
    name: "Marble cheesecake",
    description: "Philadelphia cheese with lemon zest on a light sponge cake and red currant jam",
    price: "$3.50",
    src: "../resources/catalog/dessert-1.png",
    alt: "Marble cheesecake",
  },
  {
    id: 14,
    category: "dessert",
    name: "Red velvet",
    description: "Layer cake with cream cheese frosting",
    price: "$4.00",
    src: "../resources/catalog/dessert-2.png",
    alt: "Red velvet",
  },
  {
    id: 15,
    category: "dessert",
    name: "Cheesecakes",
    description: "Soft cottage cheese pancakes with sour cream and fresh berries and sprinkled with powdered sugar",
    price: "$4.50",
    src: "../resources/catalog/dessert-3.png",
    alt: "Cheesecakes",
  },
  {
    id: 16,
    category: "dessert",
    name: "Creme brulee",
    description: "Delicate creamy dessert in a caramel basket with wild berries",
    price: "$4.00",
    src: "../resources/catalog/dessert-4.png",
    alt: "Creme brulee",
  },
  {
    id: 17,
    category: "dessert",
    name: "Pancakes",
    description: "Tender pancakes with strawberry jam and fresh strawberries",
    price: "$4.50",
    src: "../resources/catalog/dessert-5.png",
    alt: "Pancakes",
  },
  {
    id: 18,
    category: "dessert",
    name: "Honey cake",
    description: "Classic honey cake with delicate custard",
    price: "$4.50",
    src: "../resources/catalog/dessert-6.png",
    alt: "Honey cake",
  },
  {
    id: 18,
    category: "dessert",
    name: "Chocolate cake",
    description: "Cake with hot chocolate filling and nuts with dried apricots",
    price: "$5.50",
    src: "../resources/catalog/dessert-7.png",
    alt: "Chocolate cake",
  },
  {
    id: 20,
    category: "dessert",
    name: "Black forest",
    description: "A combination of thin sponge cake with cherry jam and light chocolate mousse",
    price: "$6.50",
    src: "../resources/catalog/dessert-8.png",
    alt: "Black forest",
  },
  
]

export { cardsData };